# yaml-language-server: $schema=https://raw.githubusercontent.com/cea-hpc/pcvs/refs/heads/master/pcvs/schemes/generated/profile-scheme.yml
---
compiler: "gcc"
criterion: ""
group: ""
machine: "default"
runtime: ""
