# yaml-language-server: $schema=https://raw.githubusercontent.com/cea-hpc/pcvs/refs/heads/master/pcvs/schemes/generated/runtime-scheme.yml
---
program: mpirun
criterions:
  n_mpi:
    option: "-n"
    numeric: true
    type: "argument"
    position: "after"
  n_omp:
    option: "OMP_NUM_THREADS="
    numeric: true
    position: "after"
    type: "environment"
  n_node:
    option: "-N"
    numeric: true
    position: "after"
    type: "argument"
  n_core:
    option: "-c"
    numeric: true
    position: "after"
    type: "argument"

plugin: "mpi-omp"
