# yaml-language-server: $schema=https://raw.githubusercontent.com/cea-hpc/pcvs/refs/heads/master/pcvs/schemes/generated/criterion-scheme.yml
---
n_mpi:
  subtitle: n
  values: [1, 2, 4]
n_node:
  subtitle: N
  values: [1, 2, 4]
n_core:
  subtitle: c
  values: [1, 4, 8]
